#toml ls
[[language]]
name = "toml"
formatter = { command = "taplo", args = ["fmt", "-"] }

#typescript ls
[[language]]
name = "javascript"
auto-format = true
language-servers = [
  "typescript-language-server", # optional
  "vscode-eslint-language-server",
]

[[language]]
name = "jsx"
auto-format = true
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]

[[language]]
name = "typescript"
auto-format = true
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]

[[language]]
name = "tsx"
auto-format = true
language-servers = [
  "typescript-language-server",
  "vscode-eslint-language-server",
]

#vue ls
[[language]]
name = "vue"
auto-format = true
formatter = { command = "prettier", args = ["--parser", "vue"] }
language-servers = ["typescript-language-server"]

[[language-server.typescript-language-server.config.plugins]]
name = "@vue/typescript-plugin"
location = "/home/st/.local/share/pnpm/vue-language-server"
languages = ["vue"]

#tailwind ls
[language-server.tailwindcss-ls]
command = "tailwindcss-language-server"
args = ["--stdio"]

[[language]]
name = "html"
language-servers = [ "vscode-html-language-server", "tailwindcss-ls" ]

[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "tailwindcss-ls" ]

[[language]]
name = "jsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]

[[language]]
name = "tsx"
language-servers = [ "typescript-language-server", "tailwindcss-ls" ]

[[language]]
name = "svelte"
language-servers = [ "svelteserver", "tailwindcss-ls" ]

#python ls
[[language]]
name = "python"
language-servers = [ "pyright" ]

#marksdown ls
[[language]]
name = "markdown"
language-servers = [ "marksman", "ltex-ls" ]
